// DOM referansları.
// Savunmacı kodlama: her referans null olabilir, kullanım öncesi kontrol edilir.

/** @param {string} id */
export const $ = (id) => document.getElementById(id);

export const el = {
  // Üst bar
  topBar: $('topBar'),
  backBtn: $('backBtn'),
  streakChip: $('streakChip'),
  streakValue: $('streakValue'),
  xpChip: $('xpChip'),
  xpValue: $('xpValue'),

  // Ekranlar
  onboardingScreen: $('onboarding-screen'),
  homeScreen: $('home-screen'),
  fieldScreen: $('field-screen'),
  cardsScreen: $('cards-screen'),
  quizScreen: $('quiz-screen'),
  phrasesScreen: $('phrases-screen'),
  phraseListScreen: $('phrase-list-screen'),
  dialoguesScreen: $('dialogues-screen'),
  dialogueSetupScreen: $('dialogue-setup-screen'),
  dialoguePlayScreen: $('dialogue-play-screen'),

  // Tanışma testi / alan seçimi
  wizardSteps: $('wizardSteps'),
  wizardTitle: $('wizardTitle'),
  wizardSub: $('wizardSub'),
  wizardOptions: $('wizardOptions'),
  wizardBackBtn: $('wizardBackBtn'),
  wizardDeptStep: $('wizardDeptStep'),
  wizardGroups: $('wizardGroups'),
  wizardPresets: $('wizardPresets'),
  wizardTuneToggle: $('wizardTuneToggle'),
  wizardTuneCount: $('wizardTuneCount'),
  wizardTune: $('wizardTune'),
  interestGrid: $('interestGrid'),
  interestCount: $('interestCount'),
  interestSaveBtn: $('interestSaveBtn'),

  // Anasayfa
  greetingTitle: $('greetingTitle'),
  greetingSub: $('greetingSub'),
  profileChip: $('profileChip'),
  goalRingFill: $('goalRingFill'),
  goalCount: $('goalCount'),
  goalTotal: $('goalTotal'),
  goalText: $('goalText'),
  goalSelect: $('goalSelect'),
  continueBtn: $('continueBtn'),
  editInterestsBtn: $('editInterestsBtn'),
  homePhrasesBtn: $('homePhrasesBtn'),
  homePhrasesMeta: $('homePhrasesMeta'),
  homeDialoguesBtn: $('homeDialoguesBtn'),
  homeDialoguesMeta: $('homeDialoguesMeta'),
  homeFieldList: $('homeFieldList'),
  exploreHead: $('exploreHead'),
  exploreFieldList: $('exploreFieldList'),

  // Alan detayı
  fieldHero: $('fieldHero'),
  fieldHeroIcon: $('fieldHeroIcon'),
  fieldHeroName: $('fieldHeroName'),
  fieldHeroDesc: $('fieldHeroDesc'),
  fieldHeroGhost: $('fieldHeroGhost'),
  fieldHeroFill: $('fieldHeroFill'),
  fieldHeroStat: $('fieldHeroStat'),
  fieldLevels: $('fieldLevels'),
  categoryList: $('categoryList'),

  // Kartlar
  cardsTitle: $('cardsTitle'),
  shuffleBtn: $('shuffleBtn'),
  filterBtn: $('filterBtn'),
  levelFilter: $('levelFilter'),
  quizBtn: $('quizBtn'),
  deckFill: $('deckFill'),
  counter: $('counter'),
  deck: $('deck'),
  gradeBar: $('gradeBar'),
  prevBtn: $('prevBtn'),
  nextBtn: $('nextBtn'),

  // Quiz
  quizQuestionArea: $('quiz-question-area'),
  quizResultArea: $('quiz-result-area'),
  quizFill: $('quizFill'),
  quizProgress: $('quizProgress'),
  quizSentence: $('quizSentence'),
  quizHint: $('quizHint'),
  quizOptions: $('quizOptions'),
  quizTypeForm: $('quizTypeForm'),
  quizTypeInput: $('quizTypeInput'),
  quizTypeSubmit: $('quizTypeSubmit'),
  quizTypeFeedback: $('quizTypeFeedback'),
  quizNextBtn: $('quizNextBtn'),
  quizResultEmoji: $('quizResultEmoji'),
  quizResultTitle: $('quizResultTitle'),
  quizResultText: $('quizResultText'),
  quizResultXp: $('quizResultXp'),
  quizMistakes: $('quizMistakes'),
  quizRetryBtn: $('quizRetryBtn'),
  quizBackBtn: $('quizBackBtn'),

  // Kalıplar
  phraseHomeSub: $('phraseHomeSub'),
  phraseHomeSearchBtn: $('phraseHomeSearchBtn'),
  phraseCollections: $('phraseCollections'),
  phraseCategoryGrid: $('phraseCategoryGrid'),
  phraseListHero: $('phraseListHero'),
  phraseListIcon: $('phraseListIcon'),
  phraseListName: $('phraseListName'),
  phraseListDesc: $('phraseListDesc'),
  phraseListStat: $('phraseListStat'),
  phraseSearchInput: $('phraseSearchInput'),
  phraseRegisterFilter: $('phraseRegisterFilter'),
  phraseTrToggle: $('phraseTrToggle'),
  phraseList: $('phraseList'),

  // Diyaloglar
  dialogueHomeSub: $('dialogueHomeSub'),
  dialogueLevelFilter: $('dialogueLevelFilter'),
  dialogueList: $('dialogueList'),
  dialogueSetupLevel: $('dialogueSetupLevel'),
  dialogueSetupCount: $('dialogueSetupCount'),
  dialogueSetupTitle: $('dialogueSetupTitle'),
  dialogueSetupTitleTr: $('dialogueSetupTitleTr'),
  dialogueSetupContext: $('dialogueSetupContext'),
  dialogueRoles: $('dialogueRoles'),
  dialogueModes: $('dialogueModes'),
  dialogueStartBtn: $('dialogueStartBtn'),
  dialoguePlayArea: $('dialoguePlayArea'),
  dialoguePlayTitle: $('dialoguePlayTitle'),
  dialoguePlayRole: $('dialoguePlayRole'),
  dialogueFill: $('dialogueFill'),
  dialogueCounter: $('dialogueCounter'),
  dialogueThread: $('dialogueThread'),
  dialogueTurn: $('dialogueTurn'),
  dialogueSummaryArea: $('dialogueSummaryArea'),
  dialogueSummaryTitle: $('dialogueSummaryTitle'),
  dialogueSummaryText: $('dialogueSummaryText'),
  dialogueSummaryScore: $('dialogueSummaryScore'),
  dialogueSummaryPhrases: $('dialogueSummaryPhrases'),
  dialogueReplayBtn: $('dialogueReplayBtn'),
  dialogueChangeRoleBtn: $('dialogueChangeRoleBtn'),
  dialogueFinishBtn: $('dialogueFinishBtn'),

  // Günlük deste (anasayfa kartı)
  dailyCard: $('dailyCard'),
  dailyTitle: $('dailyTitle'),
  dailyText: $('dailyText'),
  dailyProgress: $('dailyProgress'),
  dailyFill: $('dailyFill'),
  dailyProgressLabel: $('dailyProgressLabel'),
  dailyBreakdown: $('dailyBreakdown'),
  dailyNote: $('dailyNote'),
  dailyStartBtn: $('dailyStartBtn'),
  dailyExtraBtn: $('dailyExtraBtn'),
  dailySettingsBtn: $('dailySettingsBtn'),

  // Günlük özet ekranı
  dailySummaryScreen: $('daily-summary-screen'),
  dailySummaryEmoji: $('dailySummaryEmoji'),
  dailySummaryTitle: $('dailySummaryTitle'),
  dailySummaryText: $('dailySummaryText'),
  dailySummaryTime: $('dailySummaryTime'),
  dailySummaryFields: $('dailySummaryFields'),
  dailySummaryHard: $('dailySummaryHard'),
  dailyRetryBtn: $('dailyRetryBtn'),
  dailySummaryDoneBtn: $('dailySummaryDoneBtn'),

  // Günlük deste ayarları modalı
  dailySettingsModal: $('dailySettingsModal'),
  dailySettingsBackdrop: $('dailySettingsBackdrop'),
  dailySettingsClose: $('dailySettingsClose'),
  dailySettingsSave: $('dailySettingsSave'),
  dailyGoalChips: $('dailyGoalChips'),
  dailyGoalCustom: $('dailyGoalCustom'),
  dailyNewChips: $('dailyNewChips'),
  dailyModeChips: $('dailyModeChips'),
  dailyFieldChips: $('dailyFieldChips'),
  dailyRebuildBtn: $('dailyRebuildBtn'),

  // Sekme çubuğu
  tabBar: $('tabBar'),

  // Bildirimler
  toastStack: $('toastStack'),
};
